server:
  port: 9092

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
  

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/migueldoctor/SpringCloudConfig-GitRepository
   
  application:
    name: ACCOUNT-SERVICE