server:
  port: 8761

spring:
  # Spring Cloud Config Server Repository
  cloud:
    config:
      server:
        git:
          uri: https://github.com/LabsProject-Angular-Spring/ZuulConfigRepository

  application:
    name: eureka-server